version: '3'
services:
  docker-dev:
    build:
      context: .
    ports:
      - '8888:8888'
    network_mode: "host"
    # env_file:
    #   - .env
    # stdin_open: true
    # tty: true
    volumes:
      - ./:/home/devuser
      - $HOME/.vim:/home/devuser/.vim
      - $HOME/.dotfiles:/home/devuser/.dotfiles
