version: '3'
services:
  docker-dev:
    build:
      context: .
    ports:
      - '8899:8899'
    network_mode: "host"
    # env_file:
    #   - .env
    # stdin_open: true
    # tty: true
    volumes:
      - ./code:/home/devuser/code
      - ./data:/home/devuser/data
